#!/bin/bash
#安装基础服务
yum install wget -y
#安装zerotier,并且加入网络
curl -s https://install.zerotier.com | sudo bash
zerotier-cli join a09acf02333289cf
systemctl enable zerotier-one

#添加moon服务器

mkdir -p /var/lib/zerotier-one/moons.d && cd /var/lib/zerotier-one/moons.d && wget --no-cookie --no-check-certificate https://raw.githubusercontent.com/szr0728/OpenStack/main/000000986a8a957f.moon

systemctl restart zerotier-one
